platform :ios,'5.0'
pod 'PonyDebugger', '~> 0.3.0'
pod 'JSONKit',       '~> 1.4'
pod 'Reachability',  '~> 3.0.0'
pod 'AFNetworking', '~> 1.3.2'
pod 'NSLogger'
pod 'RegexKitLite'
pod 'MMDrawerController', '~> 0.4.0'
pod 'CXPhotoBrowser'
pod 'SDWebImage', '~> 3.5'
pod 'SVPullToRefresh', '~> 0.4.1'
pod 'FlatUIKit'
platform :ios, '6.0'
pod 'REFrostedViewController', '~> 2.2.1'
pod 'KKProgressTimer', :git => 'http://github.com/gin0606/KKProgressTimer.git'
