platform :ios,'5.0'
pod 'PonyDebugger', '~> 0.3.0'
pod 'JSONKit',       '~> 1.4'
pod 'Reachability',  '~> 3.0.0'
pod 'AFNetworking', '~> 1.3.2'
pod 'NSLogger'
pod 'RegexKitLite'
pod 'MMDrawerController', '~> 0.4.0'
